name:           outsort
version:        0.1.0
synopsis:       External sorting package based on Conduit
category:       Algorithms
license:        MIT
license-file:   COPYING
maintainer:     Luis Pedro Coelho <luis@luispedro.org>
ghc-options:    -Wall -O2 -threaded -fwarn-tabs
description:    >
    External (disk-backed) sorting package based on Conduit, saving
    intermediate files to disk and later merging them all.

extra-source-files:
 - README.md
 - ChangeLog

dependencies:
  - base >= 4.7 && < 5
  - async
  - bytestring
  - conduit
  - conduit-algorithms
  - conduit-extra
  - conduit-combinators
  - containers
  - deepseq
  - directory
  - exceptions
  - filepath
  - filemanip
  - primitive
  - MissingH
  - resourcet
  - temporary
  - text
  - transformers
  - transformers-base
  - safe
  - safeio
  - vector
  - vector-algorithms


source-dirs:
  - ./

executables:
  SortLines:
    main: SortLines.hs
